### ISSUE TITLE
Magic strings

### ISSUE THREAD

**Issue by smudge202** [sblackler/compose-remoting#10]
I fully expect this one to be countered... I disagree with the _string naming_ of providers.

In `DefaultCompressionFactory` for example, is the method:

```c#
public ICompressionProvider Create(string name)
```

I appreciate the concept, but wonder if there is a better way. I'm not a fan of passing around strings in code unless absolutely necessary., So the question... is it absolutely necessary?

Maybe describe the idea behind it and we can discuss possible alternatives?

**Comment by sblackler** [comment]
The idea behind this is that we attach properties to the `Message` class. So the outbound pipeline will add the properties for Encryption,Serialization,Compression with the name of each provider used. This allows the transition elements of compose to come into effect (eg: switch to JSON for debugging etc) without affecting any messages that are pending. So unless you can think of a better way for the scenario mentioned, I'd like to keep this as it provides one of the main features. Ugly yes, better way around it? Not sure. You'll see a class called `MessageProperties` which provide the keys for the properties, so i've tried to strong name where possible.

**Comment by smudge202** [comment]
Vodka isn't helping my thought process on this one, but I feel like we should have some _internal-only_ constructs that can rely on the magic strings and call out as necessary; these should not be a part of the exposed API.

That way the strings (that are a major _niggle_ right now) can continue to exist, but are kept within the package?

**Comment by smudge202** [comment]
Just to add to this; [Compose](http://github.com/smudge202/compose) has a fair amount of ugliness, I don't deny there'd be issues if it were to receive a thorough code review. However, for the most part, the code that would be brought into question is _internal sealed_.

Achieving 100% clean code is a fool's goal. Achieving 100% exposed clean code, not so much.

**Comment by sblackler** [comment]
I'm just thinking whether or not we can abuse the `ITypeNamingProvider` to cover this [see here for the default](https://github.com/sblackler/compose-remoting/blob/MemoIntegration/src/Compose.Remoting/Infrastructure/Providers/DefaultTypeNamingProvider.cs). That way at least the providers aren't declaring strings. We would still be attaching string properties to the message, but passing types around internally?

**Comment by smudge202** [comment]
Anything we can do that completely removes public exposure of strings being passed around gets my thumbs up.

**Comment by mattridgway** [comment]
Im not a great fan of magic strings. Not sure if im understand this correctly, as I dont have the code locally to follow through properly, but using them to name the classes to be able to resolve them specifically later feels like service location. 
Adding these properties to the outbound pipeline, I assume for another system to use to decode again, what if the other system has other ways of decoding, or doesn't bother decoding?
Shouldn't we have something that can look at the messages/current system and be able to decide what is the best to use.

**Comment by sblackler** [comment]
I think that this is slowly becoming the same discussion as #28 - How do we infer without service location. If we can solve that, the solution to this should be pretty apparent.

**Comment by sblackler** [comment]
I've been thinking that we could probably use something a bit more like a visitor pattern in which given a message, the provider checks to see whether it can do anything on the message and returns `true` if it has completed an action, `false` if it hasn't.

Sample usage:

    public sealed class DefaultInboundMessagePipeline : IInboundMessagePipeline
    {
        private readonly IEnumerable<ICompressionProvider> _compressionProviders;
        private readonly IEnumerable<IEncryptionProvider> _encryptionProviders;
        private readonly IMessageProcessorFactory _messageProcessorFactory;
        private readonly IEnumerable<ISerializationProvider> _serializationProviders;
        private readonly ITypeNamingProvider _typeNamingProvider;

        public DefaultInboundMessagePipeline(IMessageProcessorFactory messageProcessorFactory,
            ITypeNamingProvider typeNamingProvider,
            IEnumerable<IEncryptionProvider> encryptionProviders,
            IEnumerable<ISerializationProvider> serializationProviders,
            IEnumerable<ICompressionProvider> compressionProviders)
        {
            if (messageProcessorFactory == null)
            {
                throw new ArgumentNullException(nameof(messageProcessorFactory));
            }

            if (typeNamingProvider == null)
            {
                throw new ArgumentNullException(nameof(typeNamingProvider));
            }

            if (encryptionProviders == null)
            {
                throw new ArgumentNullException(nameof(encryptionProviders));
            }

            if (serializationProviders == null)
            {
                throw new ArgumentNullException(nameof(serializationProviders));
            }

            if (compressionProviders == null)
            {
                throw new ArgumentNullException(nameof(compressionProviders));
            }

            _messageProcessorFactory = messageProcessorFactory;
            _typeNamingProvider = typeNamingProvider;
            _encryptionProviders = encryptionProviders;
            _serializationProviders = serializationProviders;
            _compressionProviders = compressionProviders;
        }

        public void ProcessMessage(Message incomingMessage)
        {
            if (incomingMessage == null)
            {
                throw new ArgumentNullException(nameof(incomingMessage));
            }

            if (incomingMessage.BodyStream == null)
            {
                throw new InvalidMessageException(incomingMessage);
            }

            foreach (var encryptor in _encryptionProviders)
            {
                if (encryptor.Decrypt(incomingMessage))
                {
                    break;
                }
            }

            foreach (var compressor in _compressionProviders)
            {
                if (compressor.Decompress(incomingMessage))
                {
                    break;
                }
            }

            var type = _typeNamingProvider.GetType(incomingMessage.TypeName);
            foreach (var serializer in _serializationProviders)
            {
                if (serializer.Deserialise(incomingMessage, type))
                {
                    break;
                }
            }

            using (var messageProcessor = _messageProcessorFactory.Create())
            {
                messageProcessor.Process(incomingMessage);
            }
        }
    }

    public interface ICompressionProvider
    {
        bool Compress(Message message);
        bool Decompress(Message message);
    }

    public interface IEncryptionProvider : IDisposable
    {
        bool Encrypt(Message message);
        bool Decrypt(Message message);
    }

    public interface ISerializationProvider
    {
        bool Serialise(Message message, object entity);
        bool Deserialise(Message message, Type entityType);
    }

While not ideal, it allows for the separation of interfaces as discussed in #28 plus removes the factories/passing of magic strings. It is then up to each provider to decide whether it can do something with it or not. This would remove the need for the `MessageProperties` class entirely and allow the providers to figure out the inference details (though I would probably advise using the message properties to do this and not manipulate the stream).

Thoughts on this approach?

**Comment by smudge202** [comment]
This code is made soooo verbose by not one lining your argument validation (just saying).

The same example you gave: 

```c#
public sealed class DefaultInboundMessagePipeline : IInboundMessagePipeline
{
    private readonly IEnumerable<ICompressionProvider> _compressionProviders;
    private readonly IEnumerable<IEncryptionProvider> _encryptionProviders;
    private readonly IMessageProcessorFactory _messageProcessorFactory;
    private readonly IEnumerable<ISerializationProvider> _serializationProviders;
    private readonly ITypeNamingProvider _typeNamingProvider;

    public DefaultInboundMessagePipeline(IMessageProcessorFactory messageProcessorFactory,
        ITypeNamingProvider typeNamingProvider,
        IEnumerable<IEncryptionProvider> encryptionProviders,
        IEnumerable<ISerializationProvider> serializationProviders,
        IEnumerable<ICompressionProvider> compressionProviders)
    {
        if (messageProcessorFactory == null)
            throw new ArgumentNullException(nameof(messageProcessorFactory));
        if (typeNamingProvider == null)
            throw new ArgumentNullException(nameof(typeNamingProvider));
        if (encryptionProviders == null)
            throw new ArgumentNullException(nameof(encryptionProviders));
        if (serializationProviders == null)
            throw new ArgumentNullException(nameof(serializationProviders));
        if (compressionProviders == null)
            throw new ArgumentNullException(nameof(compressionProviders));

        _messageProcessorFactory = messageProcessorFactory;
        _typeNamingProvider = typeNamingProvider;
        _encryptionProviders = encryptionProviders;
        _serializationProviders = serializationProviders;
        _compressionProviders = compressionProviders;
    }

    public void ProcessMessage(Message incomingMessage)
    {
        if (incomingMessage == null)
            throw new ArgumentNullException(nameof(incomingMessage));
        if (incomingMessage.BodyStream == null)
            throw new InvalidMessageException(incomingMessage);

        foreach (var encryptor in _encryptionProviders)
            if (encryptor.Decrypt(incomingMessage)) break;

        foreach (var compressor in _compressionProviders)
            if (compressor.Decompress(incomingMessage)) break;

        var type = _typeNamingProvider.GetType(incomingMessage.TypeName);
        foreach (var serializer in _serializationProviders)
            if (serializer.Deserialise(incomingMessage, type)) break;

        using (var messageProcessor = _messageProcessorFactory.Create())
            messageProcessor.Process(incomingMessage);
    }
}

public interface ICompressionProvider
{
    bool Compress(Message message);
    bool Decompress(Message message);
}

public interface IEncryptionProvider : IDisposable
{
    bool Encrypt(Message message);
    bool Decrypt(Message message);
}

public interface ISerializationProvider
{
    bool Serialise(Message message, object entity);
    bool Deserialise(Message message, Type entityType);
}
```

Exactly the same code, equal if not greater readability.

**Comment by smudge202** [comment]
/rant

With regards to visitor pattern; yup, much prefer that approach or one like it over the magic strings. We have an internal project that follows the visitor pattern approach.

However, it's still ugly. I'll think about this one more as I go through code today.

**Comment by sblackler** [comment]
Agreed I don't like it but I can't think of a better way at the moment. Think I've hit the limit of my knowledge and need to do more research. 

This will solve the issues with the MessageProperties class and internals visible to however. 

Will be back properly later
