### ISSUE TITLE
Throw exception from factories if type not found

### ISSUE THREAD

**Issue by sblackler** [sblackler/compose-remoting#14]
So in the factories currently, I have a method such as `Create(string name)` which currently returns the default provider if we cannot find the right provider. 

I think this should be changed to throw an exception instead eg: ProviderNotFoundException

**Comment by smudge202** [comment]
I'll need to spend a few more hours on the code before I can chip in on this one, given the description you provided in #10, it's probably fair enough.

**Comment by mattridgway** [comment]
I would agree on throwing an exception - although might need to finish our "creating by name" discussion first
