### ISSUE TITLE
Remove infrastructure folders/namespaces

### ISSUE THREAD

**Issue by smudge202** [sblackler/compose-remoting#15]
As per [CA1020](https://msdn.microsoft.com/en-us/library/ms182130.aspx), I don't think the `Infrastructure` folders are necessary. By using them, the primary namespaces are going unused.

I see this akin `Interfaces` projects; it's usually a misunderstanding of component cohesion that leads to structures like that. This issues is very much _personal_ preference, so I understand if people disagree.

**Comment by sblackler** [comment]
Agreed
