### ISSUE TITLE
Xml Commentary

### ISSUE THREAD

**Issue by smudge202** [sblackler/compose-remoting#16]
As you know, I'm not a fan of comments in general. This extends to xml comments; the only difference between them is that you don't have to be examining the source code to see an xml comment (potentially making them worse than normal comments due to increased exposure).

I understand wanting to document an API, but I'd do so as exactly that, documentation. Not code comments.

I believe @mattridgway was in agreement with this one.

**Comment by mattridgway** [comment]
Death to comments. Like @smudge202 mentions, these can be dangerous, as you might not bother going to the code to find out what it is actually doing and can as easily drift out of sync like any other comment.
Creating frameworks like this is going to need documenting somewhere, but this isn't the place, as I don't think we have any intention on using a tool to auto create the documentation.

**Comment by sblackler** [comment]
Agreed
