### ISSUE TITLE
Mark MessageProperties internal

### ISSUE THREAD

**Issue by sblackler** [sblackler/compose-remoting#18]
A thought from #10. This was meant to be internal, so we should go and mark it as such.

**Comment by smudge202** [comment]
Sealed too?

**Comment by sblackler** [comment]
Agreed, I can't see any inheritors internally for the moment.

**Comment by sblackler** [comment]
Currently the class is static. I'll raise another issue on whether this should be the case or not.

**Comment by sblackler** [comment]
Clearly wasn't thinking properly earlier. The class in question is used as part of some tests. I don't particularly want to have `InternalsVisibleTo` put anywhere in here. So this may have to be a none issue for now.

**Comment by smudge202** [comment]
What's the issue with `InternalsVisibleTo`? How else will you be able to test any internal sealed default implementations?

**Comment by sblackler** [comment]
Issue https://github.com/4Com/compose-remoting/issues/9 now relates.
