### ISSUE TITLE
Duplicated strings in DefaultCompressionFactoryTests

### ISSUE THREAD

**Issue by smudge202** [sblackler/compose-remoting#19]
I notice that "Test" and "Test2" strings are duplicated on lines 23, 24, 30, and 31 in [DefaultCompressionFactoryTests](https://github.com/sblackler/compose-remoting/blob/MemoIntegration/Tests/UnitTests/Compose.Remoting.UnitTests/Infrastructure/Factories/DefaultCompressionFactoryTests.cs).

Should they be?

**Comment by sblackler** [comment]
This needs visiting as part of #10 so makes sense to fix at the same time. Probably going to find this in the other factory tests

**Comment by smudge202** [comment]
Want me to continue to raise them just so we have a tick list?

**Comment by sblackler** [comment]
sure

**Comment by sblackler** [comment]
Now under: https://github.com/4Com/compose-remoting/issues/10
