### ISSUE TITLE
[TestFixture] inconsistencies

### ISSUE THREAD

**Issue by smudge202** [sblackler/compose-remoting#21]
Although this issue would be addressed by #4, as I understand it, the `[TestFixture]` attribute is no longer a _necessity_ within nUnit? As such, you'll find it does _not_ appear in some classes (such as `DefaultInboundMessagePipelineFactoryTests`) but does appear in others (such as `DefaultEncryptionFactoryTests`).

We should look to make this more consistent, whether by adding attributes or removing them (I'm easy either way).

**Comment by sblackler** [comment]
If no longer required, I'd opt for removal as will make the source cleaner

**Comment by smudge202** [comment]
If I take this one on (or if you do!) be sure to double check; it's been a long time since I used nUnit.
