### ISSUE TITLE
Inbound, but no Outbound?

### ISSUE THREAD

**Issue by smudge202** [sblackler/compose-remoting#22]
I'm still at the point that I've barely scanned across 10% of the source code so far, but it struck me that we have _Inbound_ interfaces, but no _Outbound_ interfaces. Why is that?

_This "issue" is just a question_

**Comment by sblackler** [comment]
got an example? I think you're on about the interceptors but cant be sure

**Comment by smudge202** [comment]
`Core.Infrastructure.Factories` for example. There's an `IInboundMessagePipelineFactory` but not outbound?

**Comment by sblackler** [comment]
Ah yes. Because the inbound pipeline will come from a long running object, I needed a way to create a current pipeline (if you recall the situation in HipChat a few weeks back). The caller of the outbound pipeline is short lived and doesn't necessarily need a factory.

**Comment by smudge202** [comment]
I have the memory of a goldfish...

A goldfish with memory problems...

What was you saying?

**Comment by sblackler** [comment]
So given a long running object `x`, you need to create instances of `y` on some event. I basically asked if it was okay to have a factory where the factory took an instance of `IServiceProvider` in which the `Create` method generated instances of `y` using the `IServiceProvider` instance. I asked if this wasn't okay, how would i go about achieving the above. We deemed that the factory was okay in this instance so long as i wasnt passing the `IServiceProvider` around/this was the only place.

**Comment by sblackler** [comment]
Sorted with the architectural changes. #73
