### ISSUE TITLE
R# formatting?

### ISSUE THREAD

**Issue by smudge202** [sblackler/compose-remoting#23]
Very much a _personal_ preference thing, but I wonder if you're using ReSharper because some of the formatting doesn't feel very _human_? (Very sorry if you did it manually!) :D

For example, lines 57->60 in [DefaultMessageGeneratorTests](https://github.com/sblackler/compose-remoting/blob/MemoIntegration/Tests/UnitTests/Compose.Remoting.UnitTests/MessageHandling/DefaultMessageGeneratorTests.cs)?

**Comment by sblackler** [comment]
Yeah, that's R#. Needs cleaning up

**Comment by sblackler** [comment]
Fixed as part of the test clean up
