### ISSUE TITLE
IEnumerable vs Array

### ISSUE THREAD

**Issue by smudge202** [sblackler/compose-remoting#24]
Is there any (intended) purpose in switching between `IEnumerable<T>` and `Array<T>`? For example, in [`DefaultCompressionFactory`](https://github.com/sblackler/compose-remoting/blob/MemoIntegration/src/Compose.Remoting/Factories/DefaultCompressionFactory.cs) the Compression Providers are injected as `IEnumerable` as you'd expect (due to ServiceProvider functionality), but we use and cast as Array. Is there any reason to?

_(Being picky)_

**Comment by smudge202** [comment]
Note, they are boxed back to `IEnumerable<T>` on lines 33/39 for Linq.

**Comment by sblackler** [comment]
Hmm, Probably only for the reason that I know that I can safely enumerate the collection more than once. Would it be acceptable to allow the exception to be thrown if multiple enumerations aren't supported? If so, this can be cleaned up
