### ISSUE TITLE
Remove autocrlf CI settings

### ISSUE THREAD

**Issue by smudge202** [sblackler/compose-remoting#3]
The Crlf settings (although neat) should not be required for CI in the appveyor.yml.  They are either an obsolete artifact from addressing a previous build issue, or they're still required for the build server (which would be bad - that would mean we've managed to resolve the issue we were experiencing only on appveyor, not in other environments).

**Comment by sblackler** [comment]
Its probably obsolete now. It's related to the default serializer, which I plan to revisit properly in dev. I'll go raise an issue later for this

**Comment by smudge202** [comment]
A lot of this stuff we'll want to address so that we can get it merged into 4Com. I appreciate we've not had a discussion on OSS stuff internally yet, but there are some pretty high bars set with regards to code in 4Com repos. Thus the _Smudge-Review_. It's not a dig at you, I'm trying to get this cool stuff in with as little resistance as possible from higher up the chain. :)

I figure if the code passes a thorough review from me, hopefully @mattridgway and @bengale can't pick many faults.

**Comment by sblackler** [comment]
Yeah its no problem, it just needs a bit of a tidy really. Hopefully there is nothing major and we can start building extensions to the core pipeline soon!

**Comment by smudge202** [comment]
Agreed, can't wait to get coding on this. I'm going to run through this stuff with a fine toothed comb. Obviously, the stuff I'm raising are suggestions, not demands; they can be countered.
