### ISSUE TITLE
Generics vs Type consistency

### ISSUE THREAD

**Issue by smudge202** [sblackler/compose-remoting#30]
I imagine for code simplicity's sake, `ISerialization` provides a `Serialize` method taking a Generic, but it's counterpart `Deserialize` takes a Type / returns object.

Have to look at this from the exposed API's point of view. Code simplicity aside, they should either be both generic, or both object.

**Comment by sblackler** [comment]
I would rather remove the generic and have the object on the `Serialize` method. Making the reverse generic would be harder later in the pipeline.

**Comment by smudge202** [comment]
[`MakeGenericMethod`](https://msdn.microsoft.com/en-us/library/system.reflection.methodinfo.makegenericmethod%28v=vs.110%29.aspx) is how it's done. Bit of a nuisance. Makes the API nicer to use at cost of a little reflection.

Up to you though

**Comment by sblackler** [comment]
The base interface for handling a message is currently `IMessageHandler` which takes an object. So making both an object, for now, seems the better choice imo

**Comment by mattridgway** [comment]
@sblackler Is that going to cause you issues further down the line, like the need to re-box?
