### ISSUE TITLE
PR Pending label

### ISSUE THREAD

**Issue by smudge202** [sblackler/compose-remoting#39]
Not necessary in my opinion. Just use waffle and name branches by the issue they're addressing.

For example, if the `RemoveXmlComments` branch had been called `16-RemoveXmlComments` then in waffle you can move the issue to done once the PR has been raised, and the PR will continue to show in progress.

**Comment by smudge202** [comment]
I changed one of the existing branchs and PR's as described above. Results in this on waffle:

http://puu.sh/hjmY2/bc738ca980.png

Want me to change the rest?

**Comment by sblackler** [comment]
Yeah go for it

**Comment by sblackler** [comment]
Killed the label. All pr's resolved
