### ISSUE TITLE
Remove dependencies on solution level nuget packages

### ISSUE THREAD

**Issue by smudge202** [sblackler/compose-remoting#5]
The latest NuGet builds do not support solution level packages (we experienced a series of crashes in VS14 when trying to opening solutions containing solution level packages).

The only workaround I know of is to move the dependency to one or more of the projects (project level dependencies continue to work as expected).

We should address this sooner rather than later - the crashes provide no useful information when they occur so easy to catch people out.

**Comment by sblackler** [comment]
This is linked to #4 as the package is the NUnit runner which will no longer be needed

**Comment by smudge202** [comment]
Fair point, though one should be addressed in order to perform the merge of the PR, one can wait. Worth keeping as two separate issues?

**Comment by sblackler** [comment]
By doing #4 this will be resolved anyway. I'd keep it open for tracking in case I'm wrong
