### ISSUE TITLE
Remove now redundant git attributes file

### ISSUE THREAD

**Issue by sblackler** [sblackler/compose-remoting#8]
Its an old artifact that can now be removed

**Comment by smudge202** [comment]
I usually keep the gitattributes; fair enough if you want to kill, I don't admit to knowing what exactly it does.

**Comment by sblackler** [comment]
It's actually very similar to #3 in which I tried it on app veyor to see if that was the problem. Just forgot to remove it. I've never needed one in a solution before. If you want to keep it, fair enough, no objections, but the line endings need to come out unless you disagree with that?

**Comment by smudge202** [comment]
Ah, hadn't looked into the file. I'd say keep the file, but remove any amendments you made to fix the appveyor issue?
