### ISSUE TITLE
Collapse Transport vs Providers

### ISSUE THREAD

**Issue by smudge202** [sblackler/compose-remoting#9]
As per 4Com/compose-remoting#4, Although it's now closed, we need to see about the best way to collapse transports vs providers. Open to suggestion on this.

**Comment by sblackler** [comment]
Is this just a case of refactoring `ITransport` to `ITransportationProvider` since they both provide a service?

**Comment by smudge202** [comment]
There should be consistency either way, whether that be remove "Provider" from the other interfaces, or add to these.

Actually, I raised the issue due to the folder and namespace structure; I believe Providers/Transport live separately currently, thus should be collapsed?

**Comment by sblackler** [comment]
As part of the refactor, I would have collapsed it into the Providers folder/namespace. Makes more sense moving the transports imo

**Comment by smudge202** [comment]
Agreed, I didn't want to specify which direction the collapse should occur, but personally I'd move transports into providers.

Should we also consider the potential rename to `Extensions`? Or is `Providers` a better fit?

**Comment by sblackler** [comment]
I would suggest leaving as Providers for now, but mark it as a note to revisit once all changes are done. For me, providers makes more sense currently than extensions as they provide a service for the pipeline to consume, not necessarily an extension of the pipeline itself.

**Comment by smudge202** [comment]
True that. Would you expect future consumers to create "providers" or "extensions"? (Looking at the English only).

**Comment by sblackler** [comment]
I would expect them to consume a provider. Does it make sense semantically to consume an extension?

**Comment by smudge202** [comment]
VS does it. :)

**Comment by smudge202** [comment]
This issue is marked as complete, but I still see both namespaces in the current dev branch?

http://puu.sh/hjIuP/7e912f0166.png

**Comment by sblackler** [comment]
Yes, because its only the transports that have moved. So as mentioned, I refactored `ITransport` to be `ITransportationProvider`. However, in that namespace, the pipelines still exist for the inbound/outbound workflow. Will discuss when you're back on ts and summarise here
